version: '3.0'

services:
  php-fpm:
    build:
      context: ./docker/php
    environment:
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - ./application/backend:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - postgres
    working_dir: /symfony

  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./docker/postgres/data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    container_name: ${PROJECT_NAME}-postgres

  nginx:
    image: nginx:1.19.4-alpine
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      NGINX_HOST: ${NGINX_HOST}
      NGINX_PORT: ${NGINX_PORT}
      NGINX_DIR: /symfony/public
      PHP_FPM: php-fpm
      VIRTUAL_HOST: ${NGINX_HOST}
    working_dir: /symfony
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - ./docker/nginx/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./application/backend:/symfony
    depends_on:
      - php-fpm
    ports:
      - "80:80"


  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: ${PROJECT_NAME}-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RM_USER}
      RABBITMQ_DEFAULT_PASS: ${RM_PASSWORD}